version: "3.9"

services:
  frontend-qa:
    # Corrección: Establece el contexto en la raíz (.).
    # Apunta al Dockerfile específico de QA.
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.qa 
    container_name: frontend-qa
    ports:
      - "8080:80"
    depends_on:
      - backend-qa

  backend-qa:
    # Usa la raíz como contexto para que las rutas funcionen.
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend-qa
    environment:
      - MONGO_URI=mongodb://mongo-qa:27017/listItemDB
      - PORT=3000
    ports:
      - "3001:3000"
    depends_on:
      - mongo-qa

  mongo-qa:
    image: mongo
    container_name: mongo-qa
    ports:
      - "27017:27017"
    volumes:
      - mongoqa:/data/db

volumes:
  mongoqa: