version: "3.9"

services:
  mongo:
    image: mongo:4.4
    container_name: mongo_qa
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongoqa:/data/db

  app:
    image: todolist:v1
    container_name: todolist_app_qa
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/listItemDB
    depends_on:
      - mongo

volumes:
  mongoqa:
