version: "3.9"

services:
  frontend-prod:
    build: ./frontend
    container_name: frontend-prod
    depends_on:
      - backend-prod

  backend-prod:
    build: ./backend
    container_name: backend-prod
    environment:
      - MONGO_URI=mongodb://mongo-prod:27017/listItemDB
      - PORT=3000
    depends_on:
      - mongo-prod

  mongo-prod:
    image: mongo
    container_name: mongo-prod
    volumes:
      - mongoprod:/data/db

volumes:
  mongoprod:
